
builds:
  -
    main: ./server
    binary: vm-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    flags: -buildmode=pie
    ldflags: |-
      -s
      -w
      -X github.com/blacktop/vm-proxy/server/version.Version={{.Version}}
      -X github.com/blacktop/vm-proxy/server/version.BuildTime={{.Date}}
      -X github.com/blacktop/vm-proxy/server/version.GitCommit={{.Commit}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

changelog:
  filters:
    exclude:
      - '^small'
      - add a TODO
      - update README
  sort: asc

sign:
   artifacts: checksum

brew:
  github:
    owner: blacktop
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/blacktop/vm-proxy"
  description: "VM Proxy Server - Allows hypervisors to be controlled from docker containers."
  test: |
    system "#{bin}/vm-proxy --version"