
builds:
  -
    main: ./server/
    binary: vm-proxy
    env:
      - CGO_ENABLED=0
    goos:
      # - windows
      - darwin
      # - linux
    goarch:
      - amd64
    # flags: -buildmode=pie
    ldflags: |-
      -s
      -w
      -X github.com/blacktop/vm-proxy/server/Version={{.Version}}
      -X github.com/blacktop/vm-proxy/server/BuildTime={{.Date}}
      -X github.com/blacktop/vm-proxy/server/GitCommit={{.Commit}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

changelog:
  filters:
    exclude:
      - '^small'
      - add a TODO
      - update README
      - bump VERSION
      - fixes
      - updates
  sort: asc

sign:
   artifacts: checksum

brew:
  github:
    owner: blacktop
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/blacktop/vm-proxy"
  description: "VM Proxy Server - Allows hypervisors to be controlled from docker containers."
  plist: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>#{plist_name}</string>
        <key>Program</key>
        <string>#{bin}/vm-proxy</string>
        <key>WorkingDirectory</key>
        <string>#{HOMEBREW_PREFIX}</string>
        <key>StandardOutPath</key>
        <string>#{var}/log/vm-proxy/vm-proxy.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/vm-proxy/vm-proxy.log</string>
        <key>RunAtLoad</key>
        <true/>
      </dict>
    </plist>
    ...
  test: |
    system "#{bin}/vm-proxy --version"